# Generated by Django 5.1.4 on 2024-12-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='No Description', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
