# Generated by Django 5.1.4 on 2024-12-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0002_products_description_products_photo_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.BooleanField(default=0),
        ),
    ]
